name: CI - .NET Core 2.1 + Allure Reports

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET Core 2.1 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 2.1.818

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Run tests with Allure result output
        run: dotnet test --no-build --logger:"junit;LogFilePath=TestResults\results.xml" --results-directory TestResults

      - name: Download Allure CLI
        run: |
          Invoke-WebRequest -Uri https://github.com/allure-framework/allure2/releases/download/2.24.0/allure-2.24.0.zip -OutFile allure.zip
          Expand-Archive allure.zip -DestinationPath allure
          echo "$env:GITHUB_WORKSPACE\allure\allure-2.24.0\bin" | Out-File -Append $env:GITHUB_PATH

      - name: Generate Allure Report
        run: |
          allure\allure-2.24.0\bin\allure.bat generate TestResults --clean -o allure-report
          allure\allure-2.24.0\bin\allure.bat summary allure-report

      - name: Upload Allure Report (v4)
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
